# Generated by Django 4.2.4 on 2023-08-02 11:38

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0002_note_created_at_note_update_at_alter_note_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FF0000", image_field=None, max_length=18, samples=None
            ),
        ),
    ]
