# Generated by Django 4.2.4 on 2023-08-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0003_alter_note_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="color",
            field=models.CharField(default="#fffff", max_length=7),
        ),
    ]
