# Generated by Django 4.2.4 on 2023-08-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0004_alter_note_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="color",
            field=models.CharField(default="#FFFFFF", max_length=7),
        ),
    ]
