# Generated by Django 4.2.4 on 2023-08-02 19:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0005_alter_note_color"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={"ordering": ["-modified_at"]},
        ),
        migrations.RenameField(
            model_name="note",
            old_name="update_at",
            new_name="modified_at",
        ),
    ]
