# Generated by Django 4.2.4 on 2023-08-02 20:12

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0006_alter_note_options_rename_update_at_note_modified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="slug",
            field=models.SlugField(default="hello"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="note",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
