# Generated by Django 4.2.4 on 2023-08-28 08:25

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(
                default='+16044011234', max_length=128, region=None
            ),
            preserve_default=False,
        ),
    ]
