# Generated by Django 4.2.4 on 2023-08-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0002_remove_contact_phone_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatars'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
