# Generated by Django 4.2.4 on 2023-08-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0003_alter_contact_avatar_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='slug',
            field=models.SlugField(default='ome', max_length=100),
            preserve_default=False,
        ),
    ]
