# Generated by Django 4.2.6 on 2023-11-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0007_alter_contact_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
