# Generated by Django 4.2.6 on 2023-11-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0008_alter_contact_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
