# Generated by Django 4.2.7 on 2023-11-05 09:15

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0009_contact_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='avatar',
            field=models.ImageField(
                blank=True,
                default='avatars/User Avatar.jpg',
                null=True,
                upload_to='avatars',
                verbose_name='avatar',
            ),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name='email'
            ),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='is favorite'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='organization',
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name='organization'
            ),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name='phone number'
            ),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name='title'
            ),
        ),
    ]
