# Generated by Django 4.2.4 on 2023-08-16 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plan",
            options={"ordering": ("amount", "name")},
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "trial_end",
                    models.DateField(
                        blank=True,
                        help_text="The date at which the trial ends.             If set, overrides the computed trial end date from the plan.",
                        null=True,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="The starting date for the subscription.",
                        null=True,
                    ),
                ),
                (
                    "cancel_date",
                    models.DateField(
                        blank=True,
                        help_text="The date when the subscription was canceled.",
                        null=True,
                    ),
                ),
                (
                    "ended_at",
                    models.DateField(
                        blank=True,
                        help_text="The date when the subscription ended.",
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("canceled", "Canceled"),
                            ("ended", "Ended"),
                        ],
                        default="inactive",
                        help_text="The state the subscription is in.",
                        max_length=12,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="The plan the user is subscribed to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing.plan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who is subscribed to the plan.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
